// <auto-generated />
using BookGrid.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookGrid.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250723060601_AddAuthorsAndPublishers")]
    partial class AddAuthorsAndPublishers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookGrid.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Parijat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laxmi Prasad Devkota"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bhupi Sherchan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bishweshwar Prasad Koirala"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Madhav Prasad Ghimire"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dhruba Chandra Gautam"
                        });
                });

            modelBuilder.Entity("BookGrid.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookGrid.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nepalaya"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FinePrint"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ratna Pustak Bhandar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sajha Prakashan"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kathmandu Press"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jagadamba Publications"
                        });
                });

            modelBuilder.Entity("BookGrid.Models.Book", b =>
                {
                    b.HasOne("BookGrid.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookGrid.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BookGrid.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookGrid.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
